sudo: false  # required for the new containers

language: ruby
rvm:
#  - 1.9.3 <- No longer working
  - 2.1.0
  - 2.3.0

# install: 
#   - gem install cucumber rspec regressiontest

branches:
  only: 
    - master

#  - jruby-head
#  - jruby-19mode # JRuby in 1.9 mode
#  - 1.8.7
#  - jruby-18mode # JRuby in 1.8 mode
#  - rbx-18mode

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
